shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 15.0

planner_frequency: 20.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true

GlobalPlanner:
  use_dijkstra: true
  use_grid_path: false

  cost_factor: 0.55
  neutral_cost: 50
  lethal_cost: 253

  # Smoothing
  orientation_mode: 1
  orientation_window_size: 2
