map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.0

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.1

plugins:
- {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflation_layer, type: "costmap_2d::InflationLayer"}

obstacle_layer:
  observation_sources: scan
  enabled: true
  obstacle_range: 5.0
  raytrace_range: 5.5
  track_unknown_space: true
  combination_method: 1
  scan:
    sensor_frame: front_laser
    data_type: LaserScan
    topic: front/scan
    marking: true
    clearing: true
    min_obstacle_height: -0.5
    max_obstacle_height: 2.0
    inf_is_valid: true

inflation_layer:
  enabled: true
  cost_scaling_factor: 10.0
  inflation_radius: 0.35
